name: flutter_shader_demo
description: Shaders demo.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - shaders/fractal_pyramid.glsl
    - shaders/lines.frag
    - shaders/gradient.frag
    - shaders/gradient_h.frag
    - shaders/invert.frag
    - shaders/pixelate.frag
    - shaders/pixelate_avg.frag
    - shaders/pointillism.frag
  assets:
    - assets/
  uses-material-design: true